services:
  - type: web
    name: equaled-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SARVAM_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://equaled-ai.vercel.app
      - key: BREVO_SMTP_KEY
        sync: false
      - key: BREVO_FROM_EMAIL
        sync: false
      - key: BREVO_FROM_NAME
        sync: false
